// flow-typed signature: 17becd1d346f1153761ee64bc67040bf
// flow-typed version: <<STUB>>/browserify-bignum_v1.2.0-2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browserify-bignum'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browserify-bignum' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browserify-bignum/bignumber' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browserify-bignum/bignumber.js' {
  declare module.exports: $Exports<'browserify-bignum/bignumber'>;
}
