// flow-typed signature: 1feaec8cb9a0c548abb19b409471318d
// flow-typed version: <<STUB>>/ed2curve_v0.2.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ed2curve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ed2curve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ed2curve/ed2curve' {
  declare module.exports: any;
}

declare module 'ed2curve/ed2curve.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ed2curve/ed2curve.js' {
  declare module.exports: $Exports<'ed2curve/ed2curve'>;
}
declare module 'ed2curve/ed2curve.min.js' {
  declare module.exports: $Exports<'ed2curve/ed2curve.min'>;
}
